.gitignore
art/api/admin.py
art/api/apps.py
art/api/models.py
art/api/tests.py
art/api/views.py
art/art/urls.py
art/art/wsgi.py
art/manage.py
requirements.txt

Configures Django Rest API
-Add Django
-Add Django rest framework
```python3 manage.py runserver``` 
[#154657075](https://www.pivotaltracker.com/story/show/154657075)
N/A
Signed-off-by: Mnickii <caroline.nkirote@andela.com>

#154657075 chore: Configure Django Rest API

---

README.md

Add a coveralls badge to show test coverage
**Description of task to be done?**
Add coveralls badge to show test coverage in the `READ ME` file
[#155258121](https://www.pivotaltracker.com/story/show/155258121)
**Screenshots**

Add Coveralls Badge #155258121

---

.circleci/config.yml
art/art/settings.py
art/art/wsgi.py
requirements.txt

Add a circle integration
**Description of task to be done?**
Add cicleci configurations to trigger a circle build when a push to the remote repo is done.
[#154916157](https://www.pivotaltracker.com/story/show/154916157)
Signed-off-by: Mnickii <caroline.nkirote@andela.com>

Add Circle Ci integration  #154916157

---

README.md

Add CircleCi Status badge 
**Description of task to be done?**
Adds CircleCI status badge for the project in the README
[#155258070](https://www.pivotaltracker.com/story/show/155258070)

Add Circle Ci Badge #155258070 

---

.circleci/config.yml
.gitignore
README.md
requirements.txt

Integrates coveralls into the project
**Description of work done?**
- Add coveralls environment variables to CircleCI
- Add `run coveralls` command in CircleCI `config.yml` configuration
- Add Coveralls and Coverage to `requirements.txt`
(#155258093)[https://www.pivotaltracker.com/story/show/155258093]

Integrate Coveralls #155258093

---

art/api/admin.py
art/api/models.py
art/api/tests.py
art/api/tests/test_asset_category_model.py

-  Add the asset category model
- Create a asset category model
- Create tests for the asset category model
[#155322114](https://www.pivotaltracker.com/story/show/155322114)

[#155322114] Add Asset Category Model 

---

art/art/wsgi.py
art/manage.py
art/settings/__init__.py
art/settings/base.py
art/settings/dev.py
art/settings/prod.py

Creates multiple environment setup options
**Description of work done?**
- Create settings folder
- Separate files for different environments
- Environmental settings
**How can this be manually tested?**
> $ APP_ENV=(environment) python manage.py runserver
[#155269107](https://www.pivotaltracker.com/story/show/155269107)

Set Up Multiple Environment Settings #155269107

---

api/admin.py
api/models.py
api/tests/test_item_model_number.py

Creates `Item model number` model
**Description of work done?**
- Create `test_item_model_number.py` and add tests
**How can this be manually tested?**
> $ python manage.py test
[#155322118](https://www.pivotaltracker.com/story/show/155322118)

Create Item Model Number #155322118

---

api/models.py
api/tests/test_asset_make_model.py
api/tests/test_item_model_number.py

Creates associations between `make` and `ItemModel` models
**Description of work done?**
- Create `test_item_model_number.py` and add tests
**How can this be manually tested?**
> $ python manage.py test
[#155322122](https://www.pivotaltracker.com/story/show/155322122)

Create Item Model and Make Association #155322122

---

api/serializers.py
api/tests/test_asset_log.py
api/views.py

Allow security team member to log asset checkin and checkout  
- add checkin checkout model
- add checkin checkout serializer
- add checkin checkout view sets
Using postman `/asset-logs`
[#155922721](https://www.pivotaltracker.com/n/projects/2146417/stories/155922721)

[#155922721] Security team member can log asset checkin/checkout

---

README.md

Updates the README of the project
**Description of task to be completed?**
- Add  project description
- Add getting started details
- Describe project setup
- Describe database setup
**What are the relevant pivotal tracker stories?**
[#156755804](https://www.pivotaltracker.com/story/show/156755804)

#156755804 Update the README

---

api/tests/test_user_feedback_api.py
api/views.py

Add get_queryset for user feedback endpoint
[#156725831](https://www.pivotaltracker.com/story/show/156725831)

[#156725831] User can submit feedback via API

---

api/admin.py

Allows filtering assets by type and model number
- add filtering by model number
- add filtering by asset type
`/admin/api/asset/`
[#156990474](https://www.pivotaltracker.com/n/projects/2146417/stories/156990474)

[#156990474] Allow more filtering for assets on admin dashboard

---

api/serializers.py
api/tests/test_allocation_api.py
api/urls.py
api/views.py

Creates API endpoints for allocations
**Description of tasks done?**
- Create Allocations API tests
- Create `/api/v1/allocations` endpoints
- Allow for the `GET` and `POST` requests
**How can this be manually tested?**
> $ python manage.py test
[#157103978](https://www.pivotaltracker.com/story/show/157103978)
**Screenshots**

[#157103978]Create API Endpoints for Allocation

---

api/tests/test_allocation_api.py
api/views.py
core/models/asset.py
core/tests/test_allocation_history_model.py

Assigning an asset to a user changes its status to “Allocated” 
- add a post_save signal to change the status to `allocated`
- add test
`/allocations/`
`/assets/`
[ #157183402](https://www.pivotaltracker.com/n/projects/2146417/stories/157183402)

[#157183402] Assigning an asset to a user changes its status to “Allocated” 

---

api/serializers.py
api/tests/test_asset_make_api.py
api/urls.py
api/views.py

- Allows the user to create and view asset make via API
- add test
- add AssetMake Serializer
- add AssetTMake Viewset
How should this be manually tested?
What are the relevant pivotal tracker stories?
#157396330

[#157396330] User can see create and view asset makes via API 

---

core/models/asset.py

Fixes assets being allocated on creation

[157803270] Fix all assets being allocated

---

api/urls.py

https://www.pivotaltracker.com/story/show/157681976

[157681976] enable live testing on API docs

---

add_asset_types.py
asset_types.csv
import_util.py
post_assets.py

- Allows users to import asset types
- Import asset types.
-  Run `python add_asset_types.py`
- Follow the instruction in the terminal
- [#155922723](https://www.pivotaltracker.com/story/show/155922723)

#[155922723] Import asset types

---

assetmake.csv
post_asset_makes.py

- Allows users to import asset makes
- add asset make import script
-  Run `python post_asset_makes.py`
- Follow the instruction in the terminal
- [#155922724](https://www.pivotaltracker.com/n/projects/2146417/stories/155922724)

[#155922724] User can import asset makes into the system

---

utils/helpers.py
utils/seed_asset.py

Implement csv file import from url
- add is_valid_url function to validate url
- add get_csv_from_url function to get csv from url
• [#158254542](https://www.pivotaltracker.com/story/show/158254542)

#158254542 Import file from url 

---

utils/seed_user.py
utils/user/post_scripts.py
utils/user_sample.csv

Allows importing users from the Andela user service.
- add post user script
```python
python utils/seed_user.py
```
[#158255098](https://www.pivotaltracker.com/n/projects/2146417/stories/158255098)

[#158255098] importing users into the system

---

utils/seed_asset.py

- It adds help text to import script
- adds help text support with `argparse`
[#158254668](https://www.pivotaltracker.com/story/show/158254668)

#158254668 Add help text to import script

---

settings/dev.py

Update the list of allowed hosts in the develop environment
**Description of tasks to be completed**
• Add the G.C.P staging domain name to the list of allowed host
**What are the relevant pivotal tracker stories**
• [#158689106](https://www.pivotaltracker.com/story/show/158689106)

#158689106 Update the list of allowed host

---

api/tests/test_allocation_api.py
api/tests/test_asset_api.py
api/tests/test_asset_category_api.py
api/tests/test_asset_condition_api.py
api/tests/test_asset_incident_report_api.py
api/tests/test_asset_log.py
api/tests/test_asset_make_api.py
api/tests/test_asset_model_number_api.py
api/tests/test_asset_status_api.py
api/tests/test_asset_sub_category_api.py
api/tests/test_asset_type_api.py
api/tests/test_security_user.py
api/tests/test_user.py
api/tests/test_user_feedback_api.py
core/models/asset.py
core/models/user.py
settings/base.py

- It allows pagination on API endpoints
- Add pagination method to app settings
- Ensure no test is broken
- Hit any of the endpoints

#158555572 Allow pagination on API endpoints

---

api/tests/test_asset_api.py
api/tests/test_manage_asset_api.py
api/urls.py
api/views.py

- Split asset endpoints into `/api/v1/assets/` and `/api/v1/manage-assets/`
- creates `/api/v1/manage-assets` endpoint
- write test for `/api/v1/manage-assets` endpoint
- fix failing tests
[#158613104](https://www.pivotaltracker.com/story/show/158613104)

#158613104 Split asset endpoints

---

.circleci/config.yml
Dockerfile
scripts/deploy.sh
settings/dev.py
settings/prod.py

- Creates a continuous integration and deployment pipeline 
-  Breaks down the pipeline into three jobs namely build, tests and deployment
**Description of tasks to be completed**
• Once features are merged into the master or the develop  branch, A deployment is triggered 
that will push the new features to GCP staging or production
**What are the relevant pivotal tracker stories**
[#156802464](https://www.pivotaltracker.com/story/show/156802464)

#156802464 Implement  continuous  deployment

---

api/serializers.py
api/tests/test_asset_specs_api.py
api/urls.py
api/views.py
core/models/asset.py

- Creates AssetSpecs API endpoint
- write tests for asset specs API
- add serializer for AssetSpecs
[#158853577](https://www.pivotaltracker.com/story/show/158853577https://www.pivotaltracker.com/story/show/158853577)
- make api call on `http://127.0.0.1:8000/api/v1/asset-specs` using postman or tools like curl, see screenshot below.

#158853577 Implement asset specs API endpoint

---

settings/dev.py

**Relevant Pivotal Tracker stories**
[#158946377](https://www.pivotaltracker.com/story/show/158946377)

[#158946377] cors regex update

---

api/tests/test_asset_category_api.py
api/tests/test_asset_make_api.py
core/models/asset.py

- It validates fields before saving it in the database
- Perform `title`, `upper` methods on unique fields
- Ensure no test is broken
- Go to admin dashboard and add new asset
- None

#159077504 Field Unique Validations

---

api/serializers.py
api/tests/test_allocation_api.py
api/tests/test_asset_incident_report_api.py
api/tests/test_asset_log.py
api/tests/test_asset_status_api.py

- It refactors relations display fields
- add to_representation method to relations serializers
- fix failing tests
- Make get API calls to `AssetSubCategory`, `AssetType`, `AssetMake`, `AssetModelNumber`
`AssetLog`, `AssetStatus`, `AllocationHistory`, `AssetCondition`, `AssetIncidentReport` endpoints.
[#159112548 ](https://www.pivotaltracker.com/story/show/159112548)

#159112548 Refactor relations display 

---

api/serializers.py
api/tests/test_asset_status_api.py

- It fixes missed related fields display
- Returns user email as `reported_by` value
- Ensure no test is broken
- Test out the `asset-status` and `user-feedback` endpoints

#159168982 Fix missed related fields display

---

settings/prod.py

It adds the production domain name to prod.py file
**Description of Task to be completed?**
add the domain name to the list of allowed hosts
**Relevant pivotal tracker stories:**
#159269808

#159269808: Set up production environment

---

scripts/release.sh

https://www.pivotaltracker.com/story/show/159494305

[#159494305] add a script to add release tags

---

.circleci/config.yml
scripts/deploy.sh

- Ensures that the migrations of the latest image are done 
**Description of Task to be completed?**
- Currently, the migrations container does not migrate with  the latest docker image, this causes updated tables not to be reflected in the database
**Relevant Stories**
[#159553715](https://www.pivotaltracker.com/story/show/159553715)

#159553715: update the migrations image during deployment

---

art/urls.py
core/dashboard.py
requirements.txt
settings/base.py

- Integrate Performance profiling to the admin dashboard
- integrate django-silk
- add a custom jet dashboard to show performance profile links
- run `python manage.py migrate`
- visit app admin panel
[#155322126](https://www.pivotaltracker.com/story/show/155322126)

#155322126 Performance profiling

---

.circleci/config.yml
scripts/deploy.sh

Patches host IP addresses  as environment variables to be used  as allowed hosts 
**Relevant Stories**
[#158946377](https://www.pivotaltracker.com/story/show/158946377)

ch(hosts):Patching allowed hosts as environment variables

---

requirements.txt

Adds the gevent worker to the requirements file.
This will enable the application to start with gevent gunicorn class.
**Description of task completed.**
- Use gunicorn async classes to prevent the workers timeout issue that was causing a 502 error.

#159759006  Implement gunicorn gevent worker 

---

api/filters.py
api/tests/test_asset_api.py
api/tests/test_manage_asset_api.py
api/views.py
requirements.txt
settings/base.py

- It allows filtering of assets by querying using `model_number`, `asset_type` or `email`
-Adds model_number filter
-Adds asset_type filter
-Adds an email filter
- Test out the `assets` endpoint with admin right
- [#159994135](https://www.pivotaltracker.com/story/show/159994135)

#159994135 Filter assets  by model numbers and asset type via API.

---

api/serializers.py
api/tests/test_user.py
api/views.py

•Allows an admin to view assets assigned to a user
•Add a query-set for allocated assets
•Add UserSerializerWithAssets
•Add tests
•Test users endpoint with admin rights 
•[#160109109](https://www.pivotaltracker.com/story/show/160109109)

[#160109109]: Admin can view all assets assigned to a user

---

api/filters.py
api/tests/test_user.py
api/views.py

- It allows the admin to filter users by `cohort` or`email` or `asset_count`
- Add UserFilter class to filter module
- Write tests for admin filter users
- Test out the `users` endpoint with admin right and query by `cohort` or `email` or  `asset_count`
-

#160137335 Admin filter users

---

scripts/deploy.sh

It updates the get hosts function to align with the new GCP infrastructure
**Description of task completed.**
N/A

ch(hosts):update get hosts function

---

scripts/deploy.sh

It updates the get hosts function to align with the new GCP infrastructure
**Description of task completed.**
N/A

ch(cors):fix cors issue

---

README.md
core/models/asset.py

- It sets limit for available assets warning as an environment variable.
- create an environment variable called **ASSET_LIMIT**.
- set the variable to the limit of your choice, say 10.

#159470288 Set Limit for available assets warning as an env variable.

---

api/authentication.py
settings/base.py

https://www.pivotaltracker.com/story/show/161948300

[#161948300] use post_save for firebase custom attributes

---

api/serializers.py
api/tests/test_manage_asset_api.py

•Allows an admin to change the verification status of an asset
•Includes `verified` as one of the updatable fields
[#162050857](https://www.pivotaltracker.com/story/show/162050857)

[#162050857] Ft Allows an admin to update the verification status of an asset

---

api/filters.py
api/tests/test_user.py

https://www.pivotaltracker.com/story/show/162198454

allow multiple values to filter by for users

---

api/tests/test_filter_values_endpoint.py
api/urls.py
api/views.py

•Creates an Endpoint for filter values
•Create an Endpoint to show available filter values
[#162236652](https://www.pivotaltracker.com/story/show/162236652)

[#162236652]Ft Endpoint for filter values

---

api/tests/test_filter_values_endpoint.py
api/views.py

•Returns cohorts in a sorted format
•Sort cohorts in ascending order and return them sorted.
[#162375571](https://www.pivotaltracker.com/story/show/162375571)

[#162375571]Returns cohorts in sorted format

---

core/management/commands/import_assets.py

https://www.pivotaltracker.com/story/show/162301055

fix asset import error

---

api/tests/__init__.py
api/tests/test_asset_api.py
api/tests/test_asset_condition_api.py
api/tests/test_assets_assignee_api.py
api/tests/test_manage_asset_api.py
api/tests/test_user.py
api/views.py

`Restrict an admin to view assets and Office data from their location only.`
-  Define Location field on Viewsets for OfficeBlock, OfficeFloor, OfficeFloorSections, and OfficeWorkspace models
-  Define Location field on Viewsets for Assets, Asset
#160726559

Ft admin view their center data only#160726559

---

api/serializers/andela_centres.py
api/tests/test_andela_centre_api.py

https://www.pivotaltracker.com/story/show/163189704

[#163189704] country name in centre endpoint

---

scripts/deploy.sh

This Pull Request adds a script on the deployment script for the application. The purpose of the change is to update the docker image that will be used by the cronjob to run the `python manage.py sync_users` command.
PT Story: https://www.pivotaltracker.com/story/show/162965500

[#16296550] Update the cronjob docker image

---

Pipfile
Pipfile.lock

https://www.pivotaltracker.com/story/show/163321219
https://nvd.nist.gov/vuln/detail/CVE-2019-3498

[#163321219] upgrade django - vulnerability alert

---

api/tests/test_filter_values_endpoint.py
api/tests/test_user.py
api/views/users.py

https://www.pivotaltracker.com/story/show/163321084

[#163321084] filter cohort numbers by location

---

api/filters.py
api/tests/test_manage_asset_api.py

https://www.pivotaltracker.com/story/show/163726521

[#163726521] filter by serial numbers and partial matches

---

Pipfile
Pipfile.lock

https://www.pivotaltracker.com/story/show/164104454
https://nvd.nist.gov/vuln/detail/CVE-2019-6975

[CVE-2019-6975 ]upgrade django

---

core/models/asset.py

@MadgeKinyanjui - figured out why the notifications weren't being sent out

fix slack notif

---

core/admin.py
core/forms.py
core/management/commands/sync_users.py

To be used when the cron fails (eg now - it hasn't ran in the past couple of days)

trigger user sync manually
