AndelaOSP/art-backend

art/api/models.py
- Add verbose_name_plural to Asset Category model
- python manage.py runserver
- Go to localhost:8000/admin
- Login in
- Add a verbose_name_plural to the Asset Category model to have proper grammar in the admin dashboard
Relelvant PT story
[#155322114](https://www.pivotaltracker.com/story/show/155322114)
=> feat(category-model): add verbose_name_plural

api/serializers.py, api/tests/test_user.py, api/urls.py, api/views.py, art/urls.py
Allow users to be created from an API endpoint
- add test for functionality
- add user serializer
- add user viewset
- add user url patterns
or 
endpoint `/api/v1/user` in your browser
only admin user can add users
[#155512172](https://www.pivotaltracker.com/n/projects/2146417/stories/155512172)
=> [#155512172] Users can be created from an API endpoint

requirements.txt
- Add missing whitenoise module
=> [#155322124] Fix: Add whitenoise for Heroku

api/serializers.py, api/tests/test_item_api.py, api/tests/test_item_model.py, api/urls.py, api/views.py, art/urls.py
Allow users to view assets allocated to them via API
- add test for functionality
- add item serializer
- add item viewset
- register item url
or 
endpoint `/api-auth/login` to login user
endpoint `/api/v1/items` to view assets
Included `api-auth` route to allow user login
[#155922718](https://www.pivotaltracker.com/n/projects/2146417/stories/155922718)
[delivers #155922718
=> [#155922718] user can see assets allocated to them via API

api/tests/test_item_api.py, api/views.py
Allow users to view a specific asset details by serial number via API 
- add test for functionality
- add item viewset get object by serial number
or 
endpoint `/api-auth/login` to login user
endpoint `/api/v1/items/{serial_number}` to view asset details
[#155922719](https://www.pivotaltracker.com/n/projects/2146417/stories/155922719)
[delivers #155922719]
=> [#155922719] user can see details for a specific asset via API 

.coveragerc, api/admin.py, api/models.py, api/tests/test_security_user_model.py
- Allow the admin to add an email address for security users
- change admin dashboard view to include email address
- remove code in `def save()`  that adds custom email address in security model
- refactor tests to include email address
[#156224442](https://www.pivotaltracker.com/story/show/156224442)
=> [#156224442] Add email address for security users

api/serializers.py, api/tests/test_security_user.py, api/urls.py, api/views.py
A user can see all security users (email addresses) via the API
- add security serializer
- add security viewset
- add security url
- add test to list security users
- `python manage.py test`
- Via Postman: 
- Login to the API using your credentials
- go to the route `http://localhost:8000/api/v1/security_users/`
-  You will see a list of security users depending on whether you have added a security user in your admin dashboard
[#156267228](https://www.pivotaltracker.com/story/show/156267228)
=> [#156267228] User can see security users email addresses

api/admin.py, api/forms.py, api/tests/test_security_user_model.py
Makes the password field optional for security users
- write test for optional password
- add `SecurityUserRegistrationForm` class
- import `SecurityUserRegistrationForm`  and use it  in `SecurityUserAdmin` class
- `python manage.py runserver` AND , OR
- Login into the admin dashboard
- Add a security user and leave out the `password` and `password confirmation` fields.
- Click `Save`. You should see a `success` message indicating the user has been added.
=> [#156990530] Make password field optional for security user

core/admin.py
Change the Asset logs on admin dashboard to make sense
- add `AssetLogsAdmin` class
- add `list_display` with date, asset, checked_by, log_type columns
- add `AssetLogsAdmin` to `admin.site.register`
- Login to the admin dashboard
- click on `Asset Logs`
- you will be able to see the Asset Logs table with its columns
[#156990322](https://www.pivotaltracker.com/story/show/156990322)
=> [#156990322] Change asset log display in admin dashboard

api/serializers.py, api/tests/test_asset_api.py, api/tests/test_asset_status_api.py, api/urls.py, api/views.py, core/admin.py
Allows user to track item status via API
- add asset status serializer
- add asset status viewset
- add test
`/asset-status/`
[#157103974](https://www.pivotaltracker.com/n/projects/2146417/stories/157103974)
=> [#157103974] User can track item status via API

api/serializers.py, api/tests/test_asset_api.py
Allows user to view asset type from the API endpoint
- add `asset_type` in AssetSerializer
`/admin/api/asset/`
[#157394141](https://www.pivotaltracker.com/n/projects/2146417/stories/157394141)
=> [#157394141] user can see asset type from the API endpoint

api/serializers.py, api/tests/test_asset_category_api.py, api/urls.py, api/views.py
•Allows users to create and view asset categories via API
•add asset category endpoint
•add asset category viewset
•add asset category serializer
•python manage.py test
•postman `http://127.0.0.1:8000/api/v1/asset-categories/`
[#157396327](https://www.pivotaltracker.com/story/show/157396327)
=> feat(asset category): Create and view asset categories via API

api/serializers.py, api/tests/test_asset_sub_category_api.py, api/urls.py, api/views.py
Allows user to create and view asset sub categories via API
- add AssetSubCategory Serializer
- add AssetSubCategory Viewset
- add test
`/asset-sub-categories/`
[#157396328](https://www.pivotaltracker.com/n/projects/2146417/stories/157396328)
=> [#157396328] user can see create and view sub categories via API

api/serializers.py, api/tests/test_asset_type_api.py, api/urls.py, api/views.py
Allows user to create and view asset type via API
- add AssetTypes Serializer
- add AssetTypes Viewset
- add test
`/asset-types/`
[#157396329](https://www.pivotaltracker.com/n/projects/2146417/stories/157396329)
=> [#157396329] User can see create and view asset types via API

art/urls.py, requirements.txt, settings/base.py
- This PR adds documentation for the art-backend endpoints.
- Install django-rest-swagger
- add a `/doc` path to the url file
- Locally, navigate to `http://127.0.0.1:8000/docs/`.
- Test the endpoints available here
- The frontend developers require a doc to refer to. This addresses their program.
[#157551217](https://www.pivotaltracker.com/story/show/157551217)
=> [#157551217]: add api documentation

api/serializers.py, api/tests/test_asset_condition_api.py, api/urls.py, api/views.py
This pull request introduces adding and Asset condition via the API
This should be possible:
Add notes on the asset condition via API
I should see all asset condition notes 
I should see a single asset condition using asset condition id
python manage.py test
User could not be able to write notes on the condition of the asset via the API.
#157183399
=> Asset Condition API Endpoint

api/tests/test_asset_api.py, api/views.py
• Allow admin to view all assets via API
• Add functionality to allow admin to view all assets
• Add tests
• `python manage.py test`
• Using this URL `http://127.0.0.1:8000/api/v1/assets/` on Postman. Use a Superuser token to view all assets
• [#157682134](https://www.pivotaltracker.com/story/show/157682134)
Admin User Token
User Token
=> feat(admin view assets): Admin can view all assets via API

api/urls.py, art/urls.py, requirements.txt, settings/base.py
This PR adds documentation for the art-backend endpoints.
•Install django-rest-swagger
•Add a /doc path to the url file
How should this be manually tested?
•Locally, navigate to` http://127.0.0.1:8000/docs/`
•Test the endpoints available here
Any background context you want to provide?
The frontend developers require a doc to refer to. This addresses their program.
What are the relevant pivotal tracker stories?
[#157681976](https://www.pivotaltracker.com/story/show/157681976)
Screenshots (if appropriate)
=> chore(documentation): Add api documentation

api/serializers.py, api/tests/test_asset_api.py
- Asset model number should be displayed instead of ID on the API endpoint
- Add serializer for model_number on AssetSerializer
- FIx test
- python manage.py test
- /api/v1/assets/
- #157394192
**Before**
**After**
=> #157394192: show asset model number instead of id

api/serializers.py, api/tests/test_asset_health_api.py, api/urls.py, api/views.py
- Allows the admin to view the number of assets for each status of particular asset type and 
model
- add test
- add  AssetHeathSerializer class
- add AssetHealthCountViewSet 
python manage.py test
- 
- #157183397
=> [#157183397] Implement user can view total asset by current status

api/serializers.py, api/tests/test_security_user.py, api/urls.py, api/views.py
Allows an admin to create a security user via API
- Add SecurityUser Serializer
- Add SecurityUser ViewSet
- Add test
- `python manage.py test`
-  `/security-users/`
[ #157912326](https://www.pivotaltracker.com/n/projects/2146417/stories/157912326)
=> [#157912326] Admin can add security user via API

api/tests/test_asset_api.py, api/views.py
Implement asset filtering/searching by user email address
- adds support for email filter via 'email' query param
- test asset filtering with email
- python manage.py test
- /api/v1/assets?email=[email_address]
[#157426958](https://www.pivotaltracker.com/story/show/157426958)
=> #157426958 Implements asset filter by email address

api/serializers.py, api/tests/test_asset_api.py, api/views.py
Allows users to see allocation logs for a specific asset
- Add allocation history serializer method field
- Add test
- `python manage.py test`
-  `/assets/`
[ #157353629](https://www.pivotaltracker.com/n/projects/2146417/stories/157353629)
View from the assets endpoint
View of the previous owners
View of the previous owners
=> [#157353629] User can see allocation logs for a specific asset

api/templates/api/api-index.html, api/urls.py, art/urls.py
Create a default page to be shown when the API index is viewed
- create default page template
- map template to URLs using TemplateView
- run `python manage.py runserver`
- navigate to [http://127.0.0.1:8000/](http://127.0.0.1:8000/) or [http://127.0.0.1:8000/api/v1](http://127.0.0.1:8000/api/v1) in browser
[#157966237](https://www.pivotaltracker.com/story/show/157966237)
=> #157966237 API default page

api/tests/test_allocation_api.py, api/tests/test_asset_api.py, api/tests/test_asset_category_api.py, api/tests/test_asset_condition_api.py, api/tests/test_asset_health_api.py, api/tests/test_asset_incident_report_api.py, api/tests/test_asset_log.py, api/tests/test_asset_make_api.py, api/tests/test_asset_model_number_api.py, api/tests/test_asset_status_api.py, api/tests/test_asset_sub_category_api.py, api/tests/test_asset_type_api.py, api/urls.py
- It makes adding trailing slash optional in a request URL
- subclasses `SimpleRouter` to add option trailing comma functionality
[#158686816](https://www.pivotaltracker.com/story/show/158686816)
=> #158686816 Make trailing slash optional

core/models/user.py
Fixes 
`File "core/models/user.py", line 20, in _create_user
raise ValueError("Cohort is required")
ValueError: Cohort is required` 
error when `python manage.py createsuperuser` is run and cohort value is 0.
[#158761695](https://www.pivotaltracker.com/story/show/158761695)
=> #158761695 Fixes createsuperuser error

settings/dev.py, settings/prod.py
- Adds the frontend  staging host name to  CORS_ORIGIN_WHITELIST to enable cross-site requests
**Description of Task to be completed?**
- Whitelist frontend staging domain name 
- Create  cors origin  regex 
**Relevant Pivotal Tracker stories**
[#158946377](https://www.pivotaltracker.com/story/show/158946377)
=> #158946377: Whitelist CORS origin for staging domain name 

api/serializers.py, api/tests/test_manage_asset_api.py, api/views.py
- Implement creating asset specs via asset endpoint
- modify `AssetSerializer`'s `to_internal_values` serializer method to include asset specs
- test for specs creation via asset endpoint
[#159023098](https://www.pivotaltracker.com/story/show/159023098)
=> #159023098 Modify asset specs addition

api/filters.py, api/tests/test_asset_api.py
•Allows an admin to filter assets using the asset status
•Add current_status to the FilterSet
•Add tests
•Provide the query `current_status` to the manage-assets endpoint as an admin 
•[#160192826](https://www.pivotaltracker.com/story/show/160192826)
=> [#160192826]: Admin can filter assets by asset status

core/models/asset.py
•Sends deallocation slack messages to users
•Send deallocation slack messages upon an asset deallocation.
•As an admin, allocate an asset to a user and then deallocate the asset from the user. The user should receive a slack message informing them about the asset deallocation.
•[#160140759](https://www.pivotaltracker.com/story/show/160140759)
=> [#160140759] Allow users to get assets deallocation slack messages

api/tests/test_asset_category_api.py, api/tests/test_asset_make_api.py, api/tests/test_asset_model_number_api.py, api/tests/test_asset_sub_category_api.py, api/tests/test_asset_type_api.py, api/views.py
•Sets default ordering for 
- 	Asset Categories model
-	Asset Subcategories model
-	Asset Models model
-	Asset Makes model
-	Asset types model
•Set default ordering for the above models
•As an admin, navigate to the respective endpoints
[#160312740](https://www.pivotaltracker.com/story/show/#160312740)
=> [#160312740] Sets default ordering for the following models

api/urls.py
- Restricts api docs to staging
Ensure that `docs/` and `docs/live/` can only be accessed on staging.
Setting the `APP_ENV` to `dev` then you should be able to access the docs. Otherwise, you can't be able to access them.
[#160194424](https://www.pivotaltracker.com/story/show/160194424)
=> [#160194424] Restrict docs to staging

api/views.py
- Allows an Admin user edit and delete a security user.
- Add **put** and **delete** http verb to the existing _security-user_ endpoint.
- navigate to the **/api/v1/security-users** endpoint and try the edit and delete functionality.
=> feat[#161049350]: An admin can edit and delete a security user

api/tests/test_manage_asset_api.py, api/views.py
•Enables syncing of users on AIS to ART
•Allows only a superuser to edit an asset location
• Login as a normal user and try to update an asset location
[#162050415](https://www.pivotaltracker.com/story/show/162050415)
=> [#162050415] Allows only a superuser to edit an asset location

api/views.py
•Fixes a bug where after some assets fail to be saved, on uploading another file with no errors, fake skipped assets are reported.
•Clear the global list that holds all skipped assets while returning a response to the user.
[#162539794](https://www.pivotaltracker.com/story/show/162539794)
=> Fixes a false skipped assets on upload-assets endpoint

api/serializers/users.py
- Allows admin to change security user status.
- A verified Admin user should be able to change the status of a security user by changing the value of the _is_active_ field to either True or False.
- As an admin user, Navigate to security user endpoint and change the status of a security user.
=> Ft admin can change security user status

api/serializers/assets.py, api/tests/test_asset_log.py, core/models/asset.py
- Update test to check for log_type
- Add test
Fixes a bug: Prevent checkin or checkout of an asset more than once
* Update existing test
* Write new test
* Update save() to prevent checking in or checking out an asset more than once.
Run:
1. `python manage.py test api.tests.test_asset_log.AssetLogModelTest.test_verify_double_checkin_for_asset`
2. `python manage.py test api.tests.test_asset_log.AssetLogModelTest.test_verify_double_checkout_for_asset` 
Formerly a security user could checkin an asset more than once or checkout an asset that has been checked out already.
https://www.pivotaltracker.com/story/show/164726859
=> Bug: Fix repeating asset log-#164726859
